export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const POST_PRODUCTS = "POST_PRODUCTS";
export const PUT_PRODUCTS = "PUT_PRODUCTS";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_CREATIONS = "GET_CREATIONS"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const GET_CREATIONS_BY_ID = "GET_CREATIONS_BY_ID"
export const GET_CREATIONS_BY_USER = "GET_CREATIONS_BY_USER"
export const GET_COMPONENTS = "GET_COMPONENTS";
export const GET_CREATION_FILTERS = "GET_CREATION_FILTERS";
export const GET_CREATION_FILTERS_PRICE = "GET_CREATION_FILTERS_PRICE";
export const GET_PUBLICATION_FILTERS = "GET_PUBLICATION_FILTERS";
export const GET_PUBLICATION_FILTERS_PRICE = "GET_PUBLICATION_FILTERS_PRICE";
export const CLEAN_DETAIL = "CLEAN_DETAIL";

