export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const POST_PRODUCTS = "POST_PRODUCTS";
export const PUT_PRODUCTS = "PUT_PRODUCTS";
export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"